CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY, -- Mã sản phẩm
    IN_STOCK INT, -- Tồn kho
    PRODUCT_NAME VARCHAR(50), -- Tên sản phẩm
    MANUFACTURE VARCHAR(50), -- Nhà cung cấp
    PRICE INT,
    CATEGORY_ID INT
);

CREATE TABLE CATEGORY_LAPTOP (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 0,
    CPU VARCHAR(50),
    CORES INT,
    THREADS INT,
    CLOCK_RATE INT,
    BOOST_CLOCK INT,

    RAM INT,
    RAM_STANDARD VARCHAR(50),
    RAM_BUS_SPEED INT,
    MAX_RAM INT,
    STORAGE INT,

    SCREEN_SIZE INT,
    SCREEN_RESOLUTION VARCHAR(50),
    REFRESH_RATE INT,
    TECHNOLOGY VARCHAR(50),

    GPU VARCHAR(70),
    SOUND VARCHAR(50),

    INTERFACES VARCHAR(300),
    WIRELESS_CONNECTION VARCHAR(50),
    WEBCAM VARCHAR(50),
    OTHER_FEATURE VARCHAR(50),
    KEYBOARD_BACKLIGHT VARCHAR(50),

    DIMENSION VARCHAR(50),
    LAPTOP_WEIGHT INT,
    MATERIAL VARCHAR(50),
    BATTERY INT,
    OS VARCHAR,
    RELEASE_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_MOUSE (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 1,
    SWITCH VARCHAR(50),
    IPS INT,
    LED VARCHAR(50),
    LIFESPAN INT,
    RESPOND_RATE INT,
    DESIGN VARCHAR(50),
    BATTERY_LIFE INT,
    DIMENSION VARCHAR(50),
    MOUSE_WEIGHT INT,
    COLOR VARCHAR(50),
    TYPE_CONNECT VARCHAR(50),
    CONNECTION_RANGE INT,
    SENSOR VARCHAR(20),
    BUTTONS INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_KEYBOARD (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 2,
    SWITCH VARCHAR(50),
    MODEL VARCHAR(50),
    KEYBOARD_SIZE VARCHAR(50),
    CONNECTION_RANGE INT,
    KEYCAP_MATERIAL VARCHAR(50),
    KEYBOARD_WEIGHT INT,
    RGB VARCHAR(50),
    NUM_KEYS INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_MONITOR (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 3,
    DIMENSION VARCHAR(50),
    RESOLUTION VARCHAR(50),
    REFRESH_RATE INT,
    RESPOND_TIME INT,
    SCREEN_RATIO VARCHAR(20),
    STATIC_CONTRAST VARCHAR(20),
    BRIGHTNESS INT,
    COLOR_SPACE VARCHAR(50), 
    PANEL VARCHAR(20),
    TYPE_SCREEN VARCHAR(50),
    MONTITOR_WEIGHT INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_HEADPHONES (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 4,
    DIMENSION VARCHAR(50),
    HEADPHONES_WEIGHT VARCHAR(50),
    USE_TIME INT,
    CHARGE_TIME INT,
    CHARGING_PORT VARCHAR(50)
    MICROPHONE VARCHAR(50),
    SPEAKER VARCHAR(50),
    TYPE_CONNECT VARCHAR(50),
    CONNECTION_RANGE INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)


CREATE TABLE CATEGORY_CASEPC (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 5,
    CASE_TYPE VARCHAR(50),
    NUM_PORTS INT,
    FANS VARCHAR(100),
    CONNECTION_PORTS VARCHAR(100),
    MATERIAL VARCHAR(20),
    COLOR VARCHAR(10),
    DIMENSION VARCHAR(50),
    MBOARD_SIZE VARCHAR(50),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_COOLER (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 6,
    PORT VARCHAR(50),
    FAN_SPEED INT,
    DIMENSION VARCHAR(50),
    COLOR VARCHAR(50),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_CONSOLE (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 7,
    TYPE_CONNECT VARCHAR(50),
    KEYS INT,
    BATTERY INT,
    LED VARCHAR(50),
    BATTERY_LIFE INT,
    CHARGE_TIME INT,
    CONSOLE_WEIGHT INT,
    COLOR VARCHAR(50),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CATEGORY_TABLE (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT 8,
    MATERIAL VARCHAR(50),
    DIMENSION VARCHAR(50),
    COLOR VARCHAR(50),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)