CREATE TABLE SAN_PHAM (
    MA_SAN_PHAM VARCHAR(20) PRIMARY KEY, -- Mã sản phẩm
    SO_LUONG INT, -- Tồn kho
    TEN_SAN_PHAM VARCHAR(50), -- Tên sản phẩm
    NHA_CUNG_CAP VARCHAR(50), -- Nhà cung cấp
    GIA_SAN_PHAM INT,
    LOAI_SAN_PHAM VARCHAR(50)
);

CREATE TABLE CATEGORY_CHUOT (
    SENSOR VARCHAR(20),
    MOUSE_WEIGHT INT,
    BUTTONS INT,
    DPI INT,
    COLOR VARCHAR(50),
    DIMENSION VARCHAR(50)
)

CREATE TABLE CATEGORY_LAPTOP (
    CPU VARCHAR(20),
    CORES INT,
    THREADS INT,
    CLOCK_RATE INT,
    BOOST_CLOCK INT,
    RAM INT,
    STORAGE INT,
    GPU VARCHAR(20),
    VRAM INT,
    SCREEN_SIZE INT,
    SCREEN_RESOLUTION,
    NUM_PORTS INT,
    RELEASE_DATE DATE
)

CREATE TABLE CATEGORY_CASEPC (
    DIMENSION VARCHAR(50),
    MATERIAL VARCHAR(20),
    NUM_PORTS INT
)

CREATE TABLE CATEGORY_TAINGHE (
    TYPE_CONNECT VARCHAR(50),
    DIMENSION VARCHAR(50),
    TAINGHE_WEIGHT VARCHAR(50),
    USE_TIME INT,
    CHARGE_TIME INT
)

CREATE TABLE CATEGORY_MANHINH (
    DIMENSION VARCHAR(50),
    RESOLUTION VARCHAR(50),
    PANEL VARCHAR(20),
    RESPOND_TIME INT,
    REFRESH_RATE INT,
    BRIGHTNESS INT
)
